### ISSUE TITLE
Handling data sets

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledge-south-iec61850#19]
### Abstract

Data sets are groups of data attributes (DA) or functional constraint data objects (FCDO). They are used to simplify access to functional related groups of variables. E.g. if you want to read the most important status values of a server you don’t have to ask the server for each individual variable. Instead you define a data set (or most probably use a predefined one) that contains all the required data and request them with a single read with the data set reference as an argument.

Functions to implement:

- read data set values
- define a new data set (optional)
- delete an existing data set (optional)
- read the directory (list of variables) of the data set (optional)

**Comment by mbourhis** [comment]
.

**Comment by mbourhis** [comment]
### Remarks
* a MMS is only a value (numeric, litteral, boolean,...)
* a MMS structure does not contain the name of the value

**Comment by mbourhis** [comment]
### Remarks: for knowing the 'name' of the values
2 possibilities:
* the client already knows the name of the value it wants to read (MMS, DataSet)
* the client asks the server (for DataSet and RCB usecase) and memorizes the 'name tree', before the reception of the values

**Comment by mbourhis** [comment]
HowTo:

How to update the datamodel of the IED simulator, with libiec61850?

0/ Go into the directory that contains 'datamodel' and source code of the simulator
1/ write the CID file (by adding dataset, or anything else)
2/  Generate the code source associated to the datamodel ('static_model.c' and 'static_model.h'), with the Java provided tool './tools/model_generator/genmodel.jar'

```
java -jar ../../tools/model_generator/genmodel.jar ./simpleIO_direct_control.cid -ied simpleIO -ap accessPoint1 -out static_model -modelprefix iedModel
```
3/ rebuild the IED server simulator (make)

**Comment by mbourhis** [comment]
ToDo list for the 'Dataset' ticket:

*    update documentation (in code (Doxygen), class diagram in README)
*    add unit tests for covering the new code

**Comment by mbourhis** [comment]
### Remarks

* In input JSON configuration, if no 'data_objects' are described, all the DO of the dataset are read, but it is impossible to set the 'do_type' of the Fledge Reading.
* I have added  'discovery datamodel' functions, based on the 'getDataDirectory' API of libiec61850. But it seems the standard indicates that the results is sorted (using the alphabetic order). We don't find the proof yet (IEC61850 standard or MMS standard ?). In order to keep the same order as the datamodel, I modified a parameter in libiec61850 for my IED simulator
 (https://github.com/fledge-power/fledge-south-iec61850/blob/mbourhis/handling-datasets-To-finalize/.github/workflows/ci.yml#L81).
This issue is still open.
